## Global settings -- these settings persist for all groups
version: '1.0'  # parser config version

# imports other configs (uses relative dirs)
# import: [] -- unsupported right now -- issues with whether to override or merge settings

resources:
  max_memory: -1
  max_threads: -1

db: mongodb  # database driver

# LOCAL SETTINGS (These settings get overwritten by groups/subgroups)
tasks: []  # default tasks to perform
plugins: {}  # plugin settings
#  plugin_name:
#    setting_1: value
#    setting_2: value

plugins:  # user default plugin settings
  db:
    mongodb:
      client:
        host: 'localhost'
        port: 27017
      db:
        name: 'catstuff'
  actions:
    import:  # import plugin
      max_depth: 0
      followlinks: False
      include: []
      exclude: []
      mode: 'whitelist'

tasks: []  # override user plugin settings

## Group settings (unsupported at this time)
groups:
  default: {}