## Global settings -- these settings override default config settings
# version specifies the config version -- if not specified, assumed to be the most recent
version: '1.0'

# imports other configs (uses relative dirs)
import: []

# GLOBAL SETTINGS
resources:
  max_memory: -1
  max_threads: -1

db:
  host: 'localhost'
  port: 27017
  name: 'catstuff'
  
# default tasks to perform
tasks: []

# module settings
modules: {}
#  module_name:
#    setting_1: value
#    setting_2: value
  
## Group settings
groups:
  default: {}
  
# path: RESERVED VARIABLE